### ISSUE TITLE
Form a submission process and appropriate tooling for Editors.

### ISSUE THREAD

**Issue by aubrel** [fabacab/the-lark#1]
The Lark receives submissions currently via e-mail (Gmail), which include:

- Text (currently submitted as text documents or PDFs)
- Videos (currently submitted as external links to a Vimeo account, usually)
- Music/audio (currently submitted as attachments to the e-mail)
- Webpages (currently submitted as external links) 

We need a process by which contributors can easily submit works of any of these mediums, such that we can also easily review them asynchronously for acceptance or rejection.

**Comment by fabacab** [comment]
This is effectively complete as part of WordPress Core. Simply moving to WordPress and away from SquareSpace nets us all of this functionality for free, immediately, out of the box, and much of it is already documented in [the wiki](https://github.com/meitar/the-lark/wiki). :) The test site already provides a functional demo for all of these items, too.

I'm closing this issue and will make new, more focused issues, for any details.
